language: go
go:
  - 1.6
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - make
#script:
#  - go test -v -covermode=count -coverprofile=coverage.out ./...
#  - goveralls -coverprofile=coverage.out -service travis-ci -repotoken $COVERALLS_TOKEN
after_success:
  - ghr --token $GITHUB_TOKEN --username mudler -r docker-companion --replace --prerelease --debug pre-release release/
  - ghr --token $GITHUB_TOKEN --username mudler -r docker-companion --replace --debug $(git describe --tags) release/
