language: go
go:
  - 1.6
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - make deps
script:
  - make test
  - make lint
  - make
#script:
#  - go test -v -covermode=count -coverprofile=coverage.out ./...
#  - goveralls -coverprofile=coverage.out -service travis-ci -repotoken $COVERALLS_TOKEN
after_success:
  - git config --global user.name "Deployer" && git config --global user.email foo@bar.com
  - go get github.com/tcnksm/ghr
  - ghr -u mudler -r docker-companion --replace --debug $TRAVIS_TAG release/
